/*
 * Infeasibility Proof Pipeline (Li-Dantam)
 *
 * Pipeline:
 *   1. Sample C-space via PRM (OMPL) → label goal-connected vs not
 *   2. Collect C-obs samples from the collision checker
 *   3. Train SVM (ThunderSVM) on {goal-connected=+1, not-connected+C-obs=-1}
 *   4. Project every sample onto the SVM zero-level-set via NLOPT SLSQP
 *   5. Trace / triangulate the manifold using Gudhi Coxeter triangulation
 *
 * Dependencies: OMPL, Boost.Graph, Eigen3, ThunderSVM, NLOPT, GUDHI,
 *               libcuckoo, OpenMP, Amino
 *
 * Aayush Rath, Lakshya Jindal
 */

// Amino's compiled scene graph — generated by aarxc from your robot
// description.  Must be included as extern "C" because out.c is plain C.
extern "C" {
    #include "out.c.h"
}

#include "prm_sampler.h"
#include "svm.h"
#include "man_trace.h"
#include "kinematics.h"

#include <nlopt.hpp>

#include <ompl/base/SpaceInformation.h>
#include <ompl/base/spaces/RealVectorStateSpace.h>
#include <ompl/geometric/planners/prm/PRM.h>

#include <Eigen/Dense>
#include <iostream>
#include <fstream>
#include <vector>
#include <random>
#include <stdexcept>
#include <cassert>
#include <cmath>

namespace ob = ompl::base;
namespace og = ompl::geometric;

// ─────────────────────────────────────────────────────────────────────────────
// Global Kinematics pointer
//
// StateValidator::isValid (declared in prm_sampler.h) is defined here so it
// can reach the Kinematics object.  Set once before building the PRM.
// ─────────────────────────────────────────────────────────────────────────────
static Kinematics* g_kin = nullptr;

bool StateValidator::isValid(const ob::State* state) const {
    assert(g_kin && "StateValidator: g_kin not set before OMPL planning");
    const auto* rs = state->as<ob::RealVectorStateSpace::StateType>();
    int ndof = (int)g_kin->ndof();
    std::vector<double> q(ndof);
    for (int i = 0; i < ndof; ++i) q[i] = rs->values[i];
    return !g_kin->is_real_collision(q);
}

// ─────────────────────────────────────────────────────────────────────────────
// Stage 1 — PRM sampling
//
// Grows a PRM roadmap and classifies each milestone as goal-connected (+1)
// or not (-1).  A separate rejection-sampling pass collects C-obs points.
// ─────────────────────────────────────────────────────────────────────────────

struct SamplingResult {
    std::vector<Eigen::VectorXd> cfree_samples;  // PRM milestones (C-free)
    std::vector<int>             labels;          // +1 goal-conn / -1 otherwise
    std::vector<Eigen::VectorXd> cobs_samples;   // in-collision points
};

SamplingResult build_prm_samples(
    Kinematics&                kin,
    const std::vector<double>& bounds_lo,
    const std::vector<double>& bounds_hi,
    const Eigen::VectorXd&     q_start,
    const Eigen::VectorXd&     q_goal,
    int                        n_milestones = 2000,
    int                        n_cobs       = 500
) {
    int ndof = (int)kin.ndof();
    assert((int)bounds_lo.size() == ndof && (int)bounds_hi.size() == ndof);

    g_kin = &kin;  // expose to StateValidator

    // ── OMPL setup ────────────────────────────────────────────────────────────
    auto space = std::make_shared<ob::RealVectorStateSpace>(ndof);
    ob::RealVectorBounds ompl_bounds(ndof);
    for (int i = 0; i < ndof; ++i) {
        ompl_bounds.setLow(i,  bounds_lo[i]);
        ompl_bounds.setHigh(i, bounds_hi[i]);
    }
    space->setBounds(ompl_bounds);

    auto si = std::make_shared<ob::SpaceInformation>(space);
    si->setStateValidityChecker(std::make_shared<StateValidator>(si));
    si->setup();

    // ── Build PRM ─────────────────────────────────────────────────────────────
    PRMGraph prm(si, q_start, q_goal);
    prm.growRoadmap(n_milestones);
    prm.expandRoadmap(n_milestones / 5);  // extra connectivity pass

    const auto& G = prm.getGraph();

    // ── Extract milestones and labels ─────────────────────────────────────────
    std::vector<int> milestone_labels = prm.getMilestoneLabels();

    SamplingResult result;
    auto stateMap = boost::get(og::PRM::vertex_state_t(), G);
    for (auto v : boost::make_iterator_range(boost::vertices(G))) {
        const auto* state = stateMap[v];  // retrieve state from PRMGraph
        const auto* rs = state->as<ob::RealVectorStateSpace::StateType>();
        Eigen::VectorXd q(ndof);
        for (int i = 0; i < ndof; ++i) q[i] = rs->values[i];
        result.cfree_samples.push_back(q);
        // PRMGraph labels: 1 = goal-connected → SVM +1, else SVM -1
        result.labels.push_back(milestone_labels[v] == 1 ? +1 : -1);
    }

    // ── Collect C-obs via uniform rejection sampling ───────────────────────────
    std::mt19937 rng(42);
    std::vector<std::uniform_real_distribution<double>> dists(ndof);
    for (int i = 0; i < ndof; ++i)
        dists[i] = std::uniform_real_distribution<double>(bounds_lo[i], bounds_hi[i]);

    int collected = 0;
    while (collected < n_cobs) {
        std::vector<double> q(ndof);
        for (int i = 0; i < ndof; ++i) q[i] = dists[i](rng);
        if (kin.is_real_collision(q)) {
            Eigen::VectorXd eq(ndof);
            for (int i = 0; i < ndof; ++i) eq[i] = q[i];
            result.cobs_samples.push_back(eq);
            ++collected;
        }
    }

    return result;
}

// ─────────────────────────────────────────────────────────────────────────────
// Stage 2 — SVM training
//
// Concatenates C-free milestones (±1) with C-obs samples (always -1) and
// trains a ThunderSVM RBF classifier via the Manifold wrapper.
// ─────────────────────────────────────────────────────────────────────────────

void train_svm(Manifold& manifold, const SamplingResult& sr) {
    std::vector<Eigen::VectorXd> all_samples = sr.cfree_samples;
    all_samples.insert(all_samples.end(),
                       sr.cobs_samples.begin(), sr.cobs_samples.end());

    std::vector<float> all_labels;
    all_labels.reserve(all_samples.size());
    for (int  l : sr.labels)              all_labels.push_back((float)l);
    for (size_t i = 0; i < sr.cobs_samples.size(); ++i)
                                          all_labels.push_back(-1.0f);

    std::cout << "[SVM] Training on " << all_samples.size() << " samples ("
              << sr.cfree_samples.size() << " C-free + "
              << sr.cobs_samples.size()  << " C-obs)...\n";

    manifold.train_samples(all_samples, all_labels);
    std::cout << "[SVM] Training complete.\n";
}

// ─────────────────────────────────────────────────────────────────────────────
// Stage 3 — Projection onto the SVM manifold via NLOPT SLSQP
//
// For each seed q0 we solve:
//     minimise   ½ ‖q − q0‖²
//     subject to f(q) = 0          (SVM zero-level-set)
//                lo ≤ q ≤ hi       (joint limits)
//
// The constraint gradient is computed by central finite differences because
// ThunderSVM does not expose an analytic decision-function gradient.
// ─────────────────────────────────────────────────────────────────────────────

struct ProjectionData {
    const Eigen::VectorXd&                               q0;
    const std::function<double(const Eigen::VectorXd&)>& f;
    int                                                  ndof;
};

static double proj_objective(
    const std::vector<double>& x,
    std::vector<double>&       grad,
    void*                      raw
) {
    auto* pd  = static_cast<ProjectionData*>(raw);
    double val = 0.0;
    for (int i = 0; i < pd->ndof; ++i) {
        double d = x[i] - pd->q0[i];
        val += d * d;
        if (!grad.empty()) grad[i] = d;
    }
    return 0.5 * val;
}

static double svm_constraint(
    const std::vector<double>& x,
    std::vector<double>&       grad,
    void*                      raw
) {
    auto* pd = static_cast<ProjectionData*>(raw);
    Eigen::VectorXd q = Eigen::Map<const Eigen::VectorXd>(x.data(), pd->ndof);
    double fval = pd->f(q);

    if (!grad.empty()) {
        const double h = 1e-5;
        for (int i = 0; i < pd->ndof; ++i) {
            Eigen::VectorXd qp = q; qp[i] += h;
            Eigen::VectorXd qm = q; qm[i] -= h;
            grad[i] = (pd->f(qp) - pd->f(qm)) / (2.0 * h);
        }
    }
    return fval;
}

Eigen::VectorXd project_to_manifold(
    const Eigen::VectorXd&                               q0,
    const std::function<double(const Eigen::VectorXd&)>& f,
    const std::vector<double>&                           bounds_lo,
    const std::vector<double>&                           bounds_hi,
    double tol      = 1e-7,
    int    max_eval = 2000
) {
    int ndof = (int)q0.size();
    if (std::abs(f(q0)) < tol) return q0;  // already on manifold

    ProjectionData pd{q0, f, ndof};

    nlopt::opt opt(nlopt::LD_SLSQP, ndof);
    opt.set_lower_bounds(bounds_lo);
    opt.set_upper_bounds(bounds_hi);
    opt.set_min_objective(proj_objective, &pd);
    opt.add_equality_constraint(svm_constraint, &pd, 1e-8);
    opt.set_xtol_rel(tol);
    opt.set_ftol_rel(tol);
    opt.set_maxeval(max_eval);

    std::vector<double> x(q0.data(), q0.data() + ndof);
    double minf = 0.0;
    try {
        opt.optimize(x, minf);
    } catch (const std::exception& e) {
        // NLOPT throws on numerical failures; fall back to seed
        std::cerr << "[Project] NLOPT: " << e.what() << " — keeping seed\n";
    }
    return Eigen::Map<Eigen::VectorXd>(x.data(), ndof);
}

// Projects every C-free and C-obs sample in parallel (OpenMP).
std::vector<Eigen::VectorXd> project_all_samples(
    const SamplingResult&                                sr,
    const std::function<double(const Eigen::VectorXd&)>& f,
    const std::vector<double>&                           bounds_lo,
    const std::vector<double>&                           bounds_hi
) {
    std::vector<Eigen::VectorXd> all_samples = sr.cfree_samples;
    all_samples.insert(all_samples.end(),
                       sr.cobs_samples.begin(), sr.cobs_samples.end());

    std::vector<Eigen::VectorXd> projected(all_samples.size());

    std::cout << "[Project] Projecting " << all_samples.size()
              << " samples onto SVM manifold...\n";

    #pragma omp parallel for schedule(dynamic)
    for (int i = 0; i < (int)all_samples.size(); ++i)
        projected[i] = project_to_manifold(all_samples[i], f, bounds_lo, bounds_hi);

    std::cout << "[Project] Done.\n";
    return projected;
}

// ─────────────────────────────────────────────────────────────────────────────
// Stage 4 — Manifold tracing
//
// Hands the projected seeds to manifold_tracing() (BFS over Coxeter edges)
// and then manifold_meshing() to extract the simplicial complex.
// The lattice is centred at the seed centroid; cell_size controls resolution.
// ─────────────────────────────────────────────────────────────────────────────

using MeshMap = libcuckoo::cuckoohash_map<
    PermRep,
    std::vector<Eigen::VectorXd>,
    PermRepHash>;

MeshMap trace_svm_manifold(
    const std::function<double(const Eigen::VectorXd&)>& f,
    const std::vector<Eigen::VectorXd>&                  seeds,
    int                                                  ndof,
    double                                               cell_size = 0.05
) {
    // Centre the Coxeter lattice on the seed cloud
    Eigen::VectorXd centroid = Eigen::VectorXd::Zero(ndof);
    for (const auto& s : seeds) centroid += s;
    centroid /= (double)seeds.size();

    CoxTri ct(ndof);
    ct.change_offset(centroid);
    ct.change_matrix(cell_size * Eigen::MatrixXd::Identity(ndof, ndof));

    libcuckoo::cuckoohash_map<PermRep, Eigen::VectorXd, PermRepHash> visited;
    MeshMap mesh;

    std::cout << "[Trace] BFS tracing with " << seeds.size() << " seeds...\n";
    manifold_tracing(ndof, f, seeds, visited, ct);

    {
        auto lt = visited.lock_table();
        std::cout << "[Trace] " << lt.size() << " intersecting edges found.\n";
    }

    std::cout << "[Trace] Extracting simplicial mesh...\n";
    manifold_meshing(ndof, ct, visited, mesh);

    {
        auto lt = mesh.lock_table();
        std::cout << "[Trace] " << lt.size() << " simplices in mesh.\n";
    }

    return mesh;
}

// ─────────────────────────────────────────────────────────────────────────────
// main
// ─────────────────────────────────────────────────────────────────────────────

int main(int argc, char* argv[]) {

    // ── Load scene graph ──────────────────────────────────────────────────────
    // aa_rx_dl_sg__scenegraph is the function generated by aarxc and compiled
    // into out.c.  It populates an existing aa_rx_sg with the robot geometry.
    struct aa_rx_sg* sg = aa_rx_sg_create();
    sg = aa_rx_dl_sg__scenegraph(sg, "");

    // Load environment obstacles from JSON (optional; pass path as argv[1])
    const std::string scene_file = (argc > 1) ? argv[1] : "../scenes/scene8.json";
    try {
        add_obstacles(sg, scene_file);
    } catch (const std::exception& e) {
        std::cerr << "[Warn] Could not load obstacles: " << e.what() << "\n";
    }

    // Finalise scene graph and initialise collision context
    aa_rx_sg_init(sg);
    aa_rx_sg_cl_init(sg);

    Kinematics kin(sg);   // Kinematics takes ownership; sg destroyed in destructor
    int ndof = (int)kin.ndof();
    std::cout << "[Main] Robot loaded with " << ndof << " DOF.\n";

    // ── C-space bounds (±π per revolute joint — adjust per robot) ─────────────
    std::vector<double> lo(ndof, -M_PI);
    std::vector<double> hi(ndof,  M_PI);

    // ── Start / goal ──────────────────────────────────────────────────────────
    // TODO: replace with meaningful configurations for your problem
    Eigen::VectorXd q_start = Eigen::VectorXd::Zero(ndof);
    Eigen::VectorXd q_goal  = Eigen::VectorXd::Zero(ndof);
    q_goal[0] = 1.0;

    // =========================================================================
    // Stage 1: Build PRM and collect labelled samples
    // =========================================================================
    std::cout << "\n[Stage 1] Building PRM roadmap...\n";
    SamplingResult sr = build_prm_samples(
        kin, lo, hi, q_start, q_goal,
        /*n_milestones=*/ 2000,
        /*n_cobs=*/        500
    );

    int n_goal = 0;
    for (int l : sr.labels) if (l == +1) ++n_goal;
    std::cout << "[Stage 1] C-free milestones : " << sr.cfree_samples.size()
              << "  (goal-connected: " << n_goal
              << ",  blocked: "        << (sr.cfree_samples.size() - n_goal) << ")\n"
              << "[Stage 1] C-obs samples     : " << sr.cobs_samples.size() << "\n";

    // =========================================================================
    // Stage 2: Train SVM
    // =========================================================================
    std::cout << "\n[Stage 2] Training SVM...\n";
    Manifold manifold(ndof);
    train_svm(manifold, sr);

    // Wrap as std::function for stages 3 and 4
    std::function<double(const Eigen::VectorXd&)> f =
        [&manifold](const Eigen::VectorXd& q) { return manifold(q); };

    // =========================================================================
    // Stage 3: Project all samples onto SVM manifold (f = 0)
    // =========================================================================
    std::cout << "\n[Stage 3] Projecting onto SVM manifold...\n";
    std::vector<Eigen::VectorXd> projected = project_all_samples(sr, f, lo, hi);

    // Filter out seeds that did not converge close enough to f = 0
    std::vector<Eigen::VectorXd> seeds;
    seeds.reserve(projected.size());
    const double seed_tol = 1e-4;
    for (const auto& p : projected)
        if (std::abs(f(p)) < seed_tol) seeds.push_back(p);

    std::cout << "[Stage 3] Valid seeds: " << seeds.size()
              << " / " << projected.size() << "\n";

    if (seeds.empty()) {
        std::cerr << "[Main] No valid seeds — check SVM quality and scene.\n";
        return 1;
    }

    // =========================================================================
    // Stage 4: Manifold tracing
    // =========================================================================
    std::cout << "\n[Stage 4] Tracing SVM manifold...\n";
    MeshMap mesh = trace_svm_manifold(f, seeds, ndof, /*cell_size=*/0.05);

    // ── Write mesh points to CSV ──────────────────────────────────────────────
    {
        const std::string out_file = "manifold_mesh.csv";
        std::ofstream out(out_file);
        if (!out) {
            std::cerr << "[Main] Cannot open " << out_file << "\n";
        } else {
            auto lt = mesh.lock_table();
            for (const auto& kv : lt)
                for (const auto& pt : kv.second) {
                    for (int i = 0; i < (int)pt.size(); ++i)
                        out << pt[i] << (i + 1 < (int)pt.size() ? ',' : '\n');
                }
            std::cout << "[Main] Mesh written to " << out_file << "\n";
        }
    }

    std::cout << "\n[Main] Pipeline complete.\n";
    return 0;
}